cursor #e4e2e5
cursor_text_color #c6c6cf

foreground            #e4e2e5
background            #131316
selection_foreground  #2c303e
selection_background  #c2c6d8
url_color             #b9c5ef

color0   #131316
color1   #ff7298
color2   #77ef8a
color3   #fff972
color4   #a5b3e3
color5   #404a6e
color6   #b9c5ef
color7   #ebeffa
color8   #8f929b
color9   #ff9fb8
color10  #a5ffb4
color11  #fffba5
color12  #ced8ff
color13  #d6dfff
color14  #e5eaff
color15  #f8faff
