cursor #ebdfeb
cursor_text_color #d1c2d4

foreground            #ebdfeb
background            #171119
selection_foreground  #442059
selection_background  #e4b6f9
url_color             #e6b4ff

color0   #171119
color1   #ff7289
color2   #7fff9f
color3   #ffdc72
color4   #d59cf2
color5   #603676
color6   #e6b4ff
color7   #f9efff
color8   #a199a5
color9   #ff9fae
color10  #a5ffbb
color11  #ffe8a5
color12  #e9bfff
color13  #edcaff
color14  #f3ddff
color15  #fcf8ff
