cursor #fddadd
cursor_text_color #e7bcc0

foreground            #fddadd
background            #200e11
selection_foreground  #670021
selection_background  #ffb2bb
url_color             #ffb2bb

color0   #200e11
color1   #ff7274
color2   #9cff7f
color3   #ffe372
color4   #f29aa4
color5   #76343c
color6   #ffb2bb
color7   #ffeff1
color8   #a5999a
color9   #ff9fa0
color10  #baffa5
color11  #ffeda5
color12  #ffbdc5
color13  #ffc9cf
color14  #ffdce0
color15  #fff8f9
